#!/usr/bin/env node
/**
 * sync-engine.mjs
 *
 * Syncs the generation engine from the main project into the SDK.
 * Run this after changing ai/ code, before building the SDK.
 *
 * What it does:
 * 1. Copies ai/flows/generate_project/ → sdk/src/engine/flows/generate_project/
 * 2. Copies ai/shared/ → sdk/src/engine/shared/
 * 3. Copies ai/tools/ → sdk/src/engine/tools/
 * 4. Copies ai/prompts/ → sdk/src/engine/prompts/
 * 5. Copies prompt .md files → sdk/src/engine/prompt-files/
 * 6. Rewrites @/lib/config/models → engine/shims/models
 * 7. Rewrites @/lib/clearTemplate → engine/shims/clearTemplate
 * 8. Rewrites @/lib/config/corePrompts → engine/shims/corePrompts
 * 9. Rewrites @/lib/projectManager → engine/shims/projectManager
 * 10. Rewrites @/lib/ark-image-generate → engine/shims/imageGenerate
 * 11. Strips Supabase imports
 */

import { cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, dirname, relative, resolve } from "path";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "../..");
const SDK = resolve(dirname(new URL(import.meta.url).pathname), "..");
const ENGINE = join(SDK, "src", "engine");

console.log("🔄 Syncing engine from main project...\n");

// Clean previous engine sync
if (existsSync(ENGINE)) {
  // Keep shims and the .js bridge files
  for (const entry of readdirSync(ENGINE)) {
    if (entry === "shims") continue;
    const p = join(ENGINE, entry);
    if (entry.endsWith(".js")) continue; // keep generate.js, modify.js
    rmSync(p, { recursive: true, force: true });
  }
}

// ─── Step 1: Copy source directories ─────────────────────────────────────────

const COPY_MAP = [
  ["ai/flows/generate_project", "engine/flows/generate_project"],
  ["ai/shared", "engine/shared"],
  ["ai/tools", "engine/tools"],
  ["ai/prompts", "engine/prompts"],
];

for (const [src, dest] of COPY_MAP) {
  const srcPath = join(ROOT, src);
  const destPath = join(SDK, "src", dest);
  if (!existsSync(srcPath)) {
    console.warn(`  ⚠️  Source not found: ${src}`);
    continue;
  }
  mkdirSync(destPath, { recursive: true });
  cpSync(srcPath, destPath, {
    recursive: true, filter: (s) => {
      if (s.endsWith(".test.ts")) return false;
      if (s.endsWith(".d.ts")) return false;
      if (s.endsWith(".d.ts.map")) return false;
      if (s.endsWith(".js.map")) return false;
      if (s.endsWith(".js") && !s.endsWith(".mjs")) return false;
      if (s.includes("node_modules")) return false;
      return true;
    }
  });
  console.log(`  📋 ${src} → src/${dest}`);
}

// ─── Step 2: Copy prompt .md files ───────────────────────────────────────────

const PROMPT_DIRS = [
  ["ai/flows/generate_project/prompts", "engine/prompt-files/generate"],
  ["ai/prompts/systems", "engine/prompt-files/systems"],
];

for (const [src, dest] of PROMPT_DIRS) {
  const srcPath = join(ROOT, src);
  const destPath = join(SDK, "src", dest);
  if (!existsSync(srcPath)) continue;
  mkdirSync(destPath, { recursive: true });
  cpSync(srcPath, destPath, { recursive: true });
  console.log(`  📋 ${src} → src/${dest}`);
}

// ─── Step 3: Create shim modules ────────────────────────────────────────────

const SHIMS_DIR = join(ENGINE, "shims");
mkdirSync(SHIMS_DIR, { recursive: true });

// Shim: @/lib/config/models — lightweight model config without Supabase
writeFileSync(join(SHIMS_DIR, "models.ts"), `/**
 * SDK Shim: Model configuration (no Supabase dependency)
 * Auto-generated by sync-engine.mjs — do not edit manually.
 */

export type ModelId = string;
export const DEFAULT_MODEL: ModelId = "gpt-4o-mini";
export const MODIFY_DEFAULT_MODEL: ModelId = "gpt-4o";

export const STEP_THINKING_LEVELS = ["minimal", "low", "medium", "high"] as const;
export type StepThinkingLevel = (typeof STEP_THINKING_LEVELS)[number];

export function isStepThinkingLevel(v: string): v is StepThinkingLevel {
  return (STEP_THINKING_LEVELS as readonly string[]).includes(v);
}

let _runtimeModelId: ModelId | null = null;
const _stepModelMap = new Map<string, ModelId>();
const _stepThinkingLevelMap = new Map<string, StepThinkingLevel>();
let _sectionSkillsEnabled = false;

export function setRuntimeModelId(id: ModelId | null): void { _runtimeModelId = id; }
export function getModelId(): ModelId { return _runtimeModelId ?? process.env.OPENAI_MODEL ?? DEFAULT_MODEL; }
export function getModifyModelId(): ModelId { return _runtimeModelId ?? process.env.MODIFY_MODEL ?? MODIFY_DEFAULT_MODEL; }

export function setStepModel(stepName: string, modelId: ModelId): void { _stepModelMap.set(stepName, modelId); }
export function setStepThinkingLevel(stepName: string, level: StepThinkingLevel | null): void {
  if (level == null) _stepThinkingLevelMap.delete(stepName);
  else _stepThinkingLevelMap.set(stepName, level);
}
export function clearStepModels(): void { _stepModelMap.clear(); _stepThinkingLevelMap.clear(); }
export function getStepModel(stepName: string): ModelId | null { return _stepModelMap.get(stepName) ?? null; }
export function getModelForStep(stepName: string): ModelId { return getStepModel(stepName) ?? getModelId(); }
export function getThinkingLevelForStep(stepName: string): StepThinkingLevel | undefined { return _stepThinkingLevelMap.get(stepName); }

export function setSectionSkillsEnabled(enabled: boolean): void { _sectionSkillsEnabled = enabled; }
export function isSectionSkillsEnabled(): boolean { return _sectionSkillsEnabled; }

export function modelSupportsThinking(_modelId: string): boolean { return false; }
export async function loadStepModelsFromDB(): Promise<void> { /* no-op in SDK */ }

export function setCustomModels(_models: unknown[]): void { /* no-op */ }
export function getAllModels(): unknown[] { return []; }
export function clearStepConfig(stepName: string): void { _stepModelMap.delete(stepName); _stepThinkingLevelMap.delete(stepName); }

export const GENERATION_STEPS = [
  { id: "analyze_project_requirement", label: "需求分析" },
  { id: "plan_project", label: "项目规划" },
  { id: "generate_project_design_system", label: "设计系统" },
  { id: "apply_project_design_tokens", label: "设计 Token" },
  { id: "describe_page_sections", label: "页面分段设计" },
  { id: "preselect_skills", label: "技能匹配" },
  { id: "generate_screen", label: "整屏生成" },
  { id: "generate_section", label: "组件生成" },
  { id: "compose_page", label: "页面组合" },
  { id: "repair_build", label: "构建修复" },
] as const;
`);
console.log("  🔧 Created shim: models.ts");

// Shim: @/lib/clearTemplate
writeFileSync(join(SHIMS_DIR, "clearTemplate.ts"), `/**
 * SDK Shim: clearTemplate (no external dependency)
 */
import { existsSync, readdirSync, rmSync } from "fs";
import { join } from "path";
import { getSiteRoot } from "../tools/system/common";

export interface ClearTemplateResult { removed: string[]; error?: string; }

export function clearTemplate(): ClearTemplateResult {
  const removed: string[] = [];
  try {
    const root = getSiteRoot();
    const sectionsDir = join(root, "components", "sections");
    if (existsSync(sectionsDir)) {
      for (const f of readdirSync(sectionsDir)) {
        if (f.endsWith(".tsx") || f.endsWith(".ts")) { rmSync(join(sectionsDir, f)); removed.push("components/sections/" + f); }
      }
    }
    for (const rel of ["app/page.tsx", "app/layout.tsx", "app/globals.css", "design-system.md"]) {
      const abs = join(root, rel);
      if (existsSync(abs)) { rmSync(abs); removed.push(rel); }
    }
    const imagesDir = join(root, "public", "images");
    if (existsSync(imagesDir)) {
      for (const f of readdirSync(imagesDir)) {
        if (/\\.(png|jpg|webp)$/.test(f)) { rmSync(join(imagesDir, f)); removed.push("public/images/" + f); }
      }
    }
    const appDir = join(root, "app");
    if (existsSync(appDir)) {
      for (const e of readdirSync(appDir, { withFileTypes: true })) {
        if (e.isDirectory() && e.name !== "api") {
          const pagePath = join(appDir, e.name, "page.tsx");
          if (existsSync(pagePath)) { rmSync(pagePath); removed.push("app/" + e.name + "/page.tsx"); }
          const dir = join(appDir, e.name);
          if (readdirSync(dir).length === 0) rmSync(dir, { recursive: true });
        }
      }
    }
    return { removed };
  } catch (err) { return { removed, error: err instanceof Error ? err.message : String(err) }; }
}
`);
console.log("  🔧 Created shim: clearTemplate.ts");

// Shim: @/lib/config/corePrompts
writeFileSync(join(SHIMS_DIR, "corePrompts.ts"), `/**
 * SDK Shim: corePrompts (no Supabase)
 */
export function getCoreStepPromptOverride(_opts: { kind: string; promptId: string }): string | null { return null; }
export async function loadCoreStepPromptsFromDB(): Promise<Map<string, string>> { return new Map(); }
export function withCorePromptRuntime<T>(_opts: unknown, fn: () => Promise<T>): Promise<T> { return fn(); }
`);
console.log("  🔧 Created shim: corePrompts.ts");

// Shim: @/lib/projectManager
writeFileSync(join(SHIMS_DIR, "projectManager.ts"), `/**
 * SDK Shim: projectManager (no Supabase)
 */
import { getSiteRoot } from "../tools/system/common";

export type GenerationMode = "web" | "app";
export interface ProjectMetadata {
  id: string; userPrompt: string; status: string; generationMode?: GenerationMode;
  buildSteps?: unknown[]; modificationHistory?: unknown[]; modelId?: string;
  [key: string]: unknown;
}
export function getSiteRoot as pmGetSiteRoot(projectId: string): string { return getSiteRoot(); }
`);
// Fix the syntax error in the shim
writeFileSync(join(SHIMS_DIR, "projectManager.ts"), `/**
 * SDK Shim: projectManager (no Supabase)
 */
import { getSiteRoot } from "../tools/system/common";

export type GenerationMode = "web" | "app";
export interface ProjectMetadata {
  id: string; userPrompt: string; status: string; generationMode?: GenerationMode;
  buildSteps?: unknown[]; modificationHistory?: unknown[]; modelId?: string;
  [key: string]: unknown;
}
export function getProjectSiteRoot(_projectId: string): string { return getSiteRoot(); }
export { getProjectSiteRoot as getSiteRoot };
`);
console.log("  🔧 Created shim: projectManager.ts");

// Shim: @/lib/ark-image-generate — real implementation, reads from env vars
const imageShimContent = [
  '/**',
  ' * SDK Shim: Ark image generation',
  ' * Reads ARK_API_KEY, ARK_BASE_URL, ARK_IMAGE_MODEL from environment.',
  ' * If ARK_API_KEY is not set, image generation throws (caller handles gracefully).',
  ' */',
  '',
  'export interface ArkImageGenerateOptions {',
  '  prompt: string;',
  '  size?: string;',
  '  outputFormat?: string;',
  '  signal?: AbortSignal;',
  '}',
  '',
  'function arkBaseUrl(): string {',
  '  return (process.env.ARK_BASE_URL?.trim() || "https://ark.cn-beijing.volces.com/api/v3").replace(/\\/$/, "");',
  '}',
  '',
  'function defaultModel(): string {',
  '  return process.env.ARK_IMAGE_MODEL?.trim() || "doubao-seedream-4-0-250828";',
  '}',
  '',
  'export async function generateArkImageBase64(options: ArkImageGenerateOptions | string): Promise<string> {',
  '  const opts: ArkImageGenerateOptions = typeof options === "string" ? { prompt: options } : options;',
  '  const apiKey = process.env.ARK_API_KEY?.trim();',
  '  if (!apiKey) {',
  '    throw new Error("ARK_API_KEY is not set — image generation skipped");',
  '  }',
  '',
  '  const sizeArg = String(opts.size ?? "1k").trim();',
  '  const size = /^\\d+[kK]$/.test(sizeArg) ? `${sizeArg.slice(0, -1)}k` : sizeArg;',
  '  const url = `${arkBaseUrl()}/images/generations`;',
  '',
  '  const res = await fetch(url, {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },',
  '    body: JSON.stringify({',
  '      model: defaultModel(),',
  '      prompt: opts.prompt,',
  '      size,',
  '      response_format: "b64_json",',
  '      watermark: false,',
  '    }),',
  '    signal: opts.signal,',
  '  });',
  '',
  '  if (!res.ok) {',
  '    const text = await res.text().catch(() => "");',
  '    throw new Error(`Ark image API ${res.status}: ${text.slice(0, 500)}`);',
  '  }',
  '',
  '  const json = await res.json() as any;',
  '  if (json.error?.message) throw new Error(json.error.message);',
  '',
  '  const b64 = json.data?.[0]?.b64_json;',
  '  if (b64) return b64;',
  '',
  '  const remoteUrl = json.data?.[0]?.url;',
  '  if (remoteUrl) {',
  '    const imgRes = await fetch(remoteUrl, { signal: opts.signal });',
  '    if (!imgRes.ok) throw new Error("Failed to fetch Ark image URL");',
  '    const buf = Buffer.from(await imgRes.arrayBuffer());',
  '    return buf.toString("base64");',
  '  }',
  '',
  '  throw new Error("Ark image API returned no image data");',
  '}',
].join("\n");
writeFileSync(join(SHIMS_DIR, "imageGenerate.ts"), imageShimContent);
console.log("  🔧 Created shim: imageGenerate.ts");

// ─── Step 4: Rewrite imports in all copied .ts files ─────────────────────────

// These rewrites strip imports entirely (no replacement needed)
const STRIP_PATTERNS = [
  /import\s+\{[^}]*\}\s+from\s+["']@\/lib\/trajectory\/store["'];?\n?/g,
  /import\s+\{[^}]*\}\s+from\s+["']@\/lib\/supabase[^"']*["'];?\n?/g,
  /import\s+\{[^}]*\}\s+from\s+["']@\/lib\/auth\/[^"']*["'];?\n?/g,
  /import\s+\{[^}]*\}\s+from\s+["']@\/lib\/storage["'];?\n?/g,
  /import\s+\{[^}]*\}\s+from\s+["']\.\.\/modify_project\/[^"']*["'];?\n?/g,
];

// These map @/... paths to directories relative to sdk/src/engine/
// The actual relative path is computed per-file.
const PATH_MAPPINGS = [
  { pattern: /@\/lib\/config\/models/g, target: "engine/shims/models" },
  { pattern: /@\/lib\/clearTemplate/g, target: "engine/shims/clearTemplate" },
  { pattern: /@\/lib\/config\/corePrompts/g, target: "engine/shims/corePrompts" },
  { pattern: /@\/lib\/projectManager/g, target: "engine/shims/projectManager" },
  { pattern: /@\/lib\/ark-image-generate/g, target: "engine/shims/imageGenerate" },
  { pattern: /@\/ai\/shared\//g, target: "engine/shared/", keepSuffix: true },
  { pattern: /@\/ai\/tools\//g, target: "engine/tools/", keepSuffix: true },
  { pattern: /@\/ai\/tools(?=["'])/g, target: "engine/tools" },
  { pattern: /@\/ai\/prompts\//g, target: "engine/prompts/", keepSuffix: true },
  { pattern: /@\/ai\/flows\//g, target: "engine/flows/", keepSuffix: true },
];

function computeRelativePath(fromFile, toTarget) {
  // fromFile: absolute path of the .ts file being rewritten
  // toTarget: path relative to sdk/src/ (e.g. "engine/shims/models")
  const fromDir = dirname(fromFile);
  const toAbs = join(SDK, "src", toTarget);
  let rel = relative(fromDir, toAbs).replace(/\\/g, "/");
  if (!rel.startsWith(".")) rel = "./" + rel;
  return rel;
}

function rewriteFile(filePath) {
  let content = readFileSync(filePath, "utf-8");
  let changed = false;

  // Strip imports
  for (const pattern of STRIP_PATTERNS) {
    const before = content;
    content = content.replace(pattern, "// [SDK] stripped\n");
    if (content !== before) changed = true;
  }

  // Rewrite @/ paths to relative paths
  for (const mapping of PATH_MAPPINGS) {
    if (!mapping.pattern.test(content)) continue;
    // Reset regex lastIndex
    mapping.pattern.lastIndex = 0;

    if (mapping.keepSuffix) {
      // For paths like @/ai/shared/xxx → compute relative to engine/shared/ + keep xxx
      const baseRel = computeRelativePath(filePath, mapping.target);
      const before = content;
      content = content.replace(mapping.pattern, baseRel.endsWith("/") ? baseRel : baseRel + "/");
      if (content !== before) changed = true;
    } else {
      // For exact paths like @/lib/config/models → compute relative to engine/shims/models
      const rel = computeRelativePath(filePath, mapping.target);
      const before = content;
      // Match the full from "..." pattern and replace just the path
      content = content.replace(
        new RegExp(`from\\s+["']${mapping.pattern.source}["']`, "g"),
        `from "${rel}"`
      );
      if (content !== before) changed = true;
    }
  }

  // Also rewrite relative ../../../../lib/config/models paths
  const modelsRel = computeRelativePath(filePath, "engine/shims/models");
  content = content.replace(
    /from\s+["']\.\.\/\.\.\/\.\.\/\.\.\/lib\/config\/models["']/g,
    `from "${modelsRel}"`
  );

  if (changed || content !== readFileSync(filePath, "utf-8")) {
    writeFileSync(filePath, content, "utf-8");
  }
}

function walkAndRewrite(dir) {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkAndRewrite(fullPath);
    } else if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) {
      rewriteFile(fullPath);
    }
  }
}

walkAndRewrite(join(SDK, "src", "engine"));
console.log("\n  ✏️  Import paths rewritten");

// ─── Step 4b: Patch trajectoryCollector to add no-op saveTrajectory ──────────

const trajPath = join(SDK, "src", "engine", "flows", "generate_project", "trajectoryCollector.ts");
if (existsSync(trajPath)) {
  let content = readFileSync(trajPath, "utf-8");
  // Add a no-op saveTrajectory after the stripped import
  content = content.replace(
    "// [SDK] stripped\n",
    "// [SDK] stripped\nconst saveTrajectory = async (_opts: any) => null;\n"
  );
  writeFileSync(trajPath, content, "utf-8");
  console.log("  🔧 Patched trajectoryCollector.ts: added no-op saveTrajectory");
}

// ─── Step 5: Patch common.ts to remove WORKSPACE_ROOT/sites/ restriction ─────

const commonPath = join(SDK, "src", "engine", "tools", "system", "common.ts");
if (existsSync(commonPath)) {
  let content = readFileSync(commonPath, "utf-8");
  // Remove the setSiteRoot path validation that requires WORKSPACE_ROOT/sites/
  content = content.replace(
    /export function setSiteRoot\(path: string\): void \{[\s\S]*?_siteRoot = path;\n\}/,
    `export function setSiteRoot(path: string): void {\n  _siteRoot = path;\n}`
  );
  writeFileSync(commonPath, content, "utf-8");
  console.log("  🔧 Patched common.ts: removed setSiteRoot path restriction");
}

// ─── Step 6: Patch catalog.ts to resolve prompts from SDK package dir ────────

const catalogPath = join(SDK, "src", "engine", "prompts", "core", "catalog.ts");
if (existsSync(catalogPath)) {
  let content = readFileSync(catalogPath, "utf-8");
  // Replace process.cwd() based ROOT with __dirname based path
  // In compiled JS, __dirname points to dist/engine/prompts/core/
  // Prompt files are at dist/engine/prompt-files/generate/ and dist/engine/prompt-files/systems/
  content = content.replace(
    `const ROOT = process.cwd();`,
    `const ROOT = join(__dirname, "..", "..");  // points to dist/engine/`
  );
  // Fix resolveGeneratePromptsRoot to use prompt-files directory
  content = content.replace(
    /return join\(ROOT, "ai", "flows", getGenerateFlowName\(\), "prompts"\);/,
    `return join(ROOT, "prompt-files", "generate");`
  );
  // Fix system prompt path
  content = content.replace(
    /return join\(ROOT, "ai", "prompts", "systems", `\$\{id\}\.md`\);/,
    'return join(ROOT, "prompt-files", "systems", `${id}.md`);'
  );
  // Fix default fallback path
  content = content.replace(
    /return join\(ROOT, "ai", "prompts", `\$\{id\}\.md`\);/,
    'return join(ROOT, "prompt-files", `${id}.md`);'
  );
  // Fix modify-system path
  content = content.replace(
    /return join\(ROOT, "ai", "flows", "modify_project", "prompts", "system", `\$\{id\}\.md`\);/,
    'return join(ROOT, "prompt-files", "systems", `${id}.md`);'
  );
  writeFileSync(catalogPath, content, "utf-8");
  console.log("  🔧 Patched catalog.ts: prompt paths resolve from SDK package");
}

// ─── Done ────────────────────────────────────────────────────────────────────

console.log("\n✅ Engine sync complete!\n");
console.log("Next steps:");
console.log("  1. Update sdk/tsconfig.build.json paths if needed");
console.log("  2. Run: cd sdk && pnpm build");
console.log("  3. Test: node test-import.mjs");
